version: '3.8'

services:
  app:
    container_name: school-management
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres
    env_file: 
      - .env  # Explicitly load .env file
    networks:
      - network-school-management
    command: npm run start:dev

  postgres:
    container_name: postgres-school-management
    image: postgres:latest
    restart: always
    ports:
      - '54320:5432'
    env_file:
      - .env  # Explicitly load .env file
    volumes:
      - data_postgres:/var/lib/postgresql/data
    networks:
      - network-school-management

volumes:
  data_postgres:

networks:
  network-school-management:
